version: 2

sources: 
   - name: raw
     schema : gz_raw_data
     tables:
      - name: sales
        identifier: raw_gz_sales
        description: table des ventes 
        tests:
          - unique:
              column_name : "(orders_id || '-' || pdt_id)"

        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        freshness:
          warn_after: { count : 90, period : day }
        columns:
           - name: date_date
             description: date of purchase        
      - name: product
        identifier: raw_gz_product
        description: products_id PK / purchase_price
        columns:
            - name: products_id
              tests:
                - unique
                - not_null
      - name: ship
        identifier: raw_gz_ship
        description: orders_id / Shipping_fee / log_cost /ship_cost
        columns:
            - name : orders_id
              tests : 
                - unique

      - name: adwords
        identifier: raw_gz_adwords
        description: google adwords
        
          
      - name: bing
        identifier: raw_gz_bing
        description: bing

      - name: criteo
        identifier: raw_gz_criteo
        description: criteo

      - name: facebook
        identifier: raw_gz_facebook
        description: facebook

models:
  - name: int_campaigns
    description: table full campaign 
    tests : 
      - not_null :
          column_name : "date_date"
      - unique : 
          column_name : "(campaign_key || '-' || campaign_name || '-' || date_date)"

  - name : "int_campaigns_day"
    description : Campaigns_per_day
    tests : 
      - not_null : 
          column_name : "nb_click"

  - name :  "finance_campaigns_day"
    description: Finance join campaigns 
    tests : 
       - not_null : 
          column_name : "date_date"
      

      